### ISSUE TITLE
Provide AppImage for Linux release

### ISSUE THREAD

**Issue by tgf9** [FarPlayIO/farplay-bin#1]
Hello. I'm a Linux user running Arch Linux. I tried downloading FarPlay from here: https://farplay.io/download and selected the "tgz archive" option, but I can't get the app to run.

I tried this, but failed.
```
$ ./farplay 
./farplay: error while loading shared libraries: libunistring.so.2: cannot open shared object file: No such file or directory
```
I tried debugging a bit, but looks like only `libunistring.so.5` is available in the Arch repos.

Instead, please consider creating an AppImage release. https://appimage.org/
If there was an AppImage, then everything would just work automatically on a bunch of different distros.
```
chmod u+x farplay.AppImage
./farplay.AppImage  # <-- contains everything the app needs to run
```

**Comment by dantepfer** [comment]
Hi, sorry for the late reply, we don't check this usually. Please post to our forum at farplay.io/forum and we'll get back to you right away!
