### ISSUE TITLE
Windows sample rate conversion

### ISSUE THREAD

**Issue by gamer22026** [FarPlayIO/farplay-bin#2]
Seems like sometime between 1.0.6 and 1.1.0, the sample rate conversion stopped working in Windows. Now, on 1.1.0 when trying to use an ASIO interface at 16bit 44Khz, I get the **_The audio device can't be used by Farplay in its current configuration_** error. If I switch back to 48Khz, the error goes away.

**Comment by dantepfer** [comment]
Hi, sorry for the late reply, we don't check this space for feedback. Please post to our forum at farplay.io/forum and we'll get back to you right away!
